fix: api call relocation
Planet-NULLCAST/curriculum pull request #257
Opened 2021-09-23 06:42 UTC by jasirneoito

## Description

Some Apis are still called inside components/pages. Those are to be moved to their respective services.changed login signup [chapterName] 
 
Fixes #255 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

via postman

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2021-09-24 06:15 UTC, thealpha93 requested changes
Use `try catch` block wherever you use await

2021-09-24 06:15 UTC, thealpha93 commented on pages/login.js
>        const password = document.querySelector("#password").value;
you don't need to use `document.queryselector` here.

2021-09-24 06:15 UTC, thealpha93 commented on pages/login.js
>  						const newDate = new Date(moment().add(30, 'days')).toUTCString();
code intendation

2021-09-24 06:15 UTC, thealpha93 commented on pages/curriculum/[courseName]/[chapterName].js
> +          const data = await enrollCourse(courseName, chapterName)
need `try catch` block

2021-09-24 06:15 UTC, thealpha93 commented on pages/signup.js
> +          const data = await signUp(email, password,fName,username)
need `try catch` block

2021-09-27 04:46 UTC, jasirneoito commented on config/config.js
> +const loginUrl = "api/v1/signin";
okay

2021-09-28 05:18 UTC, merged